-- MyTopbarSystem/Components/Icons.luau
local Icons = {
	Topbar = {
		Settings = {
			Outlined = "rbxassetid://80030603886247", -- Ganti ID
			Filled = "rbxassetid://80030603886247",   -- Ganti ID
		},
		Shop = {
			Outlined = "rbxassetid://85764527349372", -- Ganti ID
			Filled = "rbxassetid://85764527349372",     -- Ganti ID
		},
		About = {
			Outlined = "rbxassetid://94511095706761",-- Ganti ID
			Filled = "rbxassetid://94511095706761",    -- Ganti ID
		},
	},
	General = {
		Checkmark = "rbxassetid://71597564625336", -- Ganti ID
		-- Tambahkan ikon lain jika perlu
	},
}

return Icons